# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intjson.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("intjson.proto", :syntax => :proto3) do
    add_message "intjson.Numbers" do
      optional :label, :string, 1
      optional :signed64, :int64, 2
      optional :unsigned64, :uint64, 3
      optional :signed32, :int32, 4
      optional :unsigned32, :uint32, 5
    end
  end
end

module Intjson
  Numbers = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("intjson.Numbers").msgclass
end
