<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intjson.proto

namespace Intjson;

use UnexpectedValueException;

/**
 * Protobuf type <code>intjson.EndingLetters</code>
 */
class EndingLetters
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>OMEGA = 1;</code>
     */
    const OMEGA = 1;
    /**
     * Generated from protobuf enum <code>PSI = 2;</code>
     */
    const PSI = 2;
    /**
     * Generated from protobuf enum <code>CHI = 3;</code>
     */
    const CHI = 3;

    private static $valueToName = [
        self::UNKNOWN => 'UNKNOWN',
        self::OMEGA => 'OMEGA',
        self::PSI => 'PSI',
        self::CHI => 'CHI',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

