<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intjson.proto

namespace Intjson;

if (false) {
    /**
     * This class is deprecated. Use Intjson\Numbers\BeginningLetters instead.
     * @deprecated
     */
    class Numbers_BeginningLetters {}
}
class_exists(Numbers\BeginningLetters::class);
@trigger_error('Intjson\Numbers_BeginningLetters is deprecated and will be removed in the next major release. Use Intjson\Numbers\BeginningLetters instead', E_USER_DEPRECATED);

