# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intjson.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='intjson.proto',
  package='intjson',
  syntax='proto3',
  serialized_options=b'Z\rproto/intjson',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rintjson.proto\x12\x07intjson\"d\n\x07Numbers\x12\r\n\x05label\x18\x01 \x01(\t\x12\x10\n\x08signed64\x18\x02 \x01(\x03\x12\x12\n\nunsigned64\x18\x03 \x01(\x04\x12\x10\n\x08signed32\x18\x04 \x01(\x05\x12\x12\n\nunsigned32\x18\x05 \x01(\rB\x0fZ\rproto/intjsonb\x06proto3'
)




_NUMBERS = _descriptor.Descriptor(
  name='Numbers',
  full_name='intjson.Numbers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='intjson.Numbers.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signed64', full_name='intjson.Numbers.signed64', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unsigned64', full_name='intjson.Numbers.unsigned64', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signed32', full_name='intjson.Numbers.signed32', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unsigned32', full_name='intjson.Numbers.unsigned32', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['Numbers'] = _NUMBERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Numbers = _reflection.GeneratedProtocolMessageType('Numbers', (_message.Message,), {
  'DESCRIPTOR' : _NUMBERS,
  '__module__' : 'intjson_pb2'
  # @@protoc_insertion_point(class_scope:intjson.Numbers)
  })
_sym_db.RegisterMessage(Numbers)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
