# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intjson.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='intjson.proto',
  package='intjson',
  syntax='proto3',
  serialized_options=b'Z\rproto/intjson',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rintjson.proto\x12\x07intjson\"\xa5\x01\n\x07Numbers\x12\r\n\x05label\x18\x01 \x01(\t\x12\x10\n\x08signed64\x18\x02 \x01(\x03\x12\x12\n\nunsigned64\x18\x03 \x01(\x04\x12\x10\n\x08signed32\x18\x04 \x01(\x05\x12\x12\n\nunsigned32\x18\x05 \x01(\r\"?\n\x10\x42\x65ginningLetters\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x41LPHA\x10\x01\x12\x08\n\x04\x42\x45TA\x10\x02\x12\t\n\x05GAMMA\x10\x03*9\n\rEndingLetters\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05OMEGA\x10\x01\x12\x07\n\x03PSI\x10\x02\x12\x07\n\x03\x43HI\x10\x03\x42\x0fZ\rproto/intjsonb\x06proto3'
)

_ENDINGLETTERS = _descriptor.EnumDescriptor(
  name='EndingLetters',
  full_name='intjson.EndingLetters',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OMEGA', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PSI', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHI', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=194,
  serialized_end=251,
)
_sym_db.RegisterEnumDescriptor(_ENDINGLETTERS)

EndingLetters = enum_type_wrapper.EnumTypeWrapper(_ENDINGLETTERS)
UNKNOWN = 0
OMEGA = 1
PSI = 2
CHI = 3


_NUMBERS_BEGINNINGLETTERS = _descriptor.EnumDescriptor(
  name='BeginningLetters',
  full_name='intjson.Numbers.BeginningLetters',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ALPHA', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BETA', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GAMMA', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=129,
  serialized_end=192,
)
_sym_db.RegisterEnumDescriptor(_NUMBERS_BEGINNINGLETTERS)


_NUMBERS = _descriptor.Descriptor(
  name='Numbers',
  full_name='intjson.Numbers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='intjson.Numbers.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signed64', full_name='intjson.Numbers.signed64', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unsigned64', full_name='intjson.Numbers.unsigned64', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signed32', full_name='intjson.Numbers.signed32', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unsigned32', full_name='intjson.Numbers.unsigned32', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NUMBERS_BEGINNINGLETTERS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=192,
)

_NUMBERS_BEGINNINGLETTERS.containing_type = _NUMBERS
DESCRIPTOR.message_types_by_name['Numbers'] = _NUMBERS
DESCRIPTOR.enum_types_by_name['EndingLetters'] = _ENDINGLETTERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Numbers = _reflection.GeneratedProtocolMessageType('Numbers', (_message.Message,), {
  'DESCRIPTOR' : _NUMBERS,
  '__module__' : 'intjson_pb2'
  # @@protoc_insertion_point(class_scope:intjson.Numbers)
  })
_sym_db.RegisterMessage(Numbers)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
