// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: intjson.proto

package intjson;

public final class Intjson {
  private Intjson() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NumbersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:intjson.Numbers)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string label = 1;</code>
     */
    java.lang.String getLabel();
    /**
     * <code>string label = 1;</code>
     */
    com.google.protobuf.ByteString
        getLabelBytes();

    /**
     * <code>int64 signed64 = 2;</code>
     */
    long getSigned64();

    /**
     * <code>uint64 unsigned64 = 3;</code>
     */
    long getUnsigned64();

    /**
     * <code>int32 signed32 = 4;</code>
     */
    int getSigned32();

    /**
     * <code>uint32 unsigned32 = 5;</code>
     */
    int getUnsigned32();
  }
  /**
   * Protobuf type {@code intjson.Numbers}
   */
  public  static final class Numbers extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:intjson.Numbers)
      NumbersOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Numbers.newBuilder() to construct.
    private Numbers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Numbers() {
      label_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Numbers();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Numbers(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              label_ = s;
              break;
            }
            case 16: {

              signed64_ = input.readInt64();
              break;
            }
            case 24: {

              unsigned64_ = input.readUInt64();
              break;
            }
            case 32: {

              signed32_ = input.readInt32();
              break;
            }
            case 40: {

              unsigned32_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return intjson.Intjson.internal_static_intjson_Numbers_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return intjson.Intjson.internal_static_intjson_Numbers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              intjson.Intjson.Numbers.class, intjson.Intjson.Numbers.Builder.class);
    }

    public static final int LABEL_FIELD_NUMBER = 1;
    private volatile java.lang.Object label_;
    /**
     * <code>string label = 1;</code>
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      }
    }
    /**
     * <code>string label = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNED64_FIELD_NUMBER = 2;
    private long signed64_;
    /**
     * <code>int64 signed64 = 2;</code>
     */
    public long getSigned64() {
      return signed64_;
    }

    public static final int UNSIGNED64_FIELD_NUMBER = 3;
    private long unsigned64_;
    /**
     * <code>uint64 unsigned64 = 3;</code>
     */
    public long getUnsigned64() {
      return unsigned64_;
    }

    public static final int SIGNED32_FIELD_NUMBER = 4;
    private int signed32_;
    /**
     * <code>int32 signed32 = 4;</code>
     */
    public int getSigned32() {
      return signed32_;
    }

    public static final int UNSIGNED32_FIELD_NUMBER = 5;
    private int unsigned32_;
    /**
     * <code>uint32 unsigned32 = 5;</code>
     */
    public int getUnsigned32() {
      return unsigned32_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLabelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, label_);
      }
      if (signed64_ != 0L) {
        output.writeInt64(2, signed64_);
      }
      if (unsigned64_ != 0L) {
        output.writeUInt64(3, unsigned64_);
      }
      if (signed32_ != 0) {
        output.writeInt32(4, signed32_);
      }
      if (unsigned32_ != 0) {
        output.writeUInt32(5, unsigned32_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLabelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, label_);
      }
      if (signed64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, signed64_);
      }
      if (unsigned64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, unsigned64_);
      }
      if (signed32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, signed32_);
      }
      if (unsigned32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, unsigned32_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof intjson.Intjson.Numbers)) {
        return super.equals(obj);
      }
      intjson.Intjson.Numbers other = (intjson.Intjson.Numbers) obj;

      if (!getLabel()
          .equals(other.getLabel())) return false;
      if (getSigned64()
          != other.getSigned64()) return false;
      if (getUnsigned64()
          != other.getUnsigned64()) return false;
      if (getSigned32()
          != other.getSigned32()) return false;
      if (getUnsigned32()
          != other.getUnsigned32()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LABEL_FIELD_NUMBER;
      hash = (53 * hash) + getLabel().hashCode();
      hash = (37 * hash) + SIGNED64_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSigned64());
      hash = (37 * hash) + UNSIGNED64_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUnsigned64());
      hash = (37 * hash) + SIGNED32_FIELD_NUMBER;
      hash = (53 * hash) + getSigned32();
      hash = (37 * hash) + UNSIGNED32_FIELD_NUMBER;
      hash = (53 * hash) + getUnsigned32();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static intjson.Intjson.Numbers parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static intjson.Intjson.Numbers parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static intjson.Intjson.Numbers parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static intjson.Intjson.Numbers parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static intjson.Intjson.Numbers parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static intjson.Intjson.Numbers parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static intjson.Intjson.Numbers parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static intjson.Intjson.Numbers parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static intjson.Intjson.Numbers parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static intjson.Intjson.Numbers parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static intjson.Intjson.Numbers parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static intjson.Intjson.Numbers parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(intjson.Intjson.Numbers prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code intjson.Numbers}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:intjson.Numbers)
        intjson.Intjson.NumbersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return intjson.Intjson.internal_static_intjson_Numbers_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return intjson.Intjson.internal_static_intjson_Numbers_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                intjson.Intjson.Numbers.class, intjson.Intjson.Numbers.Builder.class);
      }

      // Construct using intjson.Intjson.Numbers.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        label_ = "";

        signed64_ = 0L;

        unsigned64_ = 0L;

        signed32_ = 0;

        unsigned32_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return intjson.Intjson.internal_static_intjson_Numbers_descriptor;
      }

      @java.lang.Override
      public intjson.Intjson.Numbers getDefaultInstanceForType() {
        return intjson.Intjson.Numbers.getDefaultInstance();
      }

      @java.lang.Override
      public intjson.Intjson.Numbers build() {
        intjson.Intjson.Numbers result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public intjson.Intjson.Numbers buildPartial() {
        intjson.Intjson.Numbers result = new intjson.Intjson.Numbers(this);
        result.label_ = label_;
        result.signed64_ = signed64_;
        result.unsigned64_ = unsigned64_;
        result.signed32_ = signed32_;
        result.unsigned32_ = unsigned32_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof intjson.Intjson.Numbers) {
          return mergeFrom((intjson.Intjson.Numbers)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(intjson.Intjson.Numbers other) {
        if (other == intjson.Intjson.Numbers.getDefaultInstance()) return this;
        if (!other.getLabel().isEmpty()) {
          label_ = other.label_;
          onChanged();
        }
        if (other.getSigned64() != 0L) {
          setSigned64(other.getSigned64());
        }
        if (other.getUnsigned64() != 0L) {
          setUnsigned64(other.getUnsigned64());
        }
        if (other.getSigned32() != 0) {
          setSigned32(other.getSigned32());
        }
        if (other.getUnsigned32() != 0) {
          setUnsigned32(other.getUnsigned32());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        intjson.Intjson.Numbers parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (intjson.Intjson.Numbers) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object label_ = "";
      /**
       * <code>string label = 1;</code>
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string label = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string label = 1;</code>
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string label = 1;</code>
       */
      public Builder clearLabel() {
        
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <code>string label = 1;</code>
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        label_ = value;
        onChanged();
        return this;
      }

      private long signed64_ ;
      /**
       * <code>int64 signed64 = 2;</code>
       */
      public long getSigned64() {
        return signed64_;
      }
      /**
       * <code>int64 signed64 = 2;</code>
       */
      public Builder setSigned64(long value) {
        
        signed64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 signed64 = 2;</code>
       */
      public Builder clearSigned64() {
        
        signed64_ = 0L;
        onChanged();
        return this;
      }

      private long unsigned64_ ;
      /**
       * <code>uint64 unsigned64 = 3;</code>
       */
      public long getUnsigned64() {
        return unsigned64_;
      }
      /**
       * <code>uint64 unsigned64 = 3;</code>
       */
      public Builder setUnsigned64(long value) {
        
        unsigned64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 unsigned64 = 3;</code>
       */
      public Builder clearUnsigned64() {
        
        unsigned64_ = 0L;
        onChanged();
        return this;
      }

      private int signed32_ ;
      /**
       * <code>int32 signed32 = 4;</code>
       */
      public int getSigned32() {
        return signed32_;
      }
      /**
       * <code>int32 signed32 = 4;</code>
       */
      public Builder setSigned32(int value) {
        
        signed32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 signed32 = 4;</code>
       */
      public Builder clearSigned32() {
        
        signed32_ = 0;
        onChanged();
        return this;
      }

      private int unsigned32_ ;
      /**
       * <code>uint32 unsigned32 = 5;</code>
       */
      public int getUnsigned32() {
        return unsigned32_;
      }
      /**
       * <code>uint32 unsigned32 = 5;</code>
       */
      public Builder setUnsigned32(int value) {
        
        unsigned32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 unsigned32 = 5;</code>
       */
      public Builder clearUnsigned32() {
        
        unsigned32_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:intjson.Numbers)
    }

    // @@protoc_insertion_point(class_scope:intjson.Numbers)
    private static final intjson.Intjson.Numbers DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new intjson.Intjson.Numbers();
    }

    public static intjson.Intjson.Numbers getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Numbers>
        PARSER = new com.google.protobuf.AbstractParser<Numbers>() {
      @java.lang.Override
      public Numbers parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Numbers(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Numbers> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Numbers> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public intjson.Intjson.Numbers getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_intjson_Numbers_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_intjson_Numbers_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rintjson.proto\022\007intjson\"d\n\007Numbers\022\r\n\005l" +
      "abel\030\001 \001(\t\022\020\n\010signed64\030\002 \001(\003\022\022\n\nunsigned" +
      "64\030\003 \001(\004\022\020\n\010signed32\030\004 \001(\005\022\022\n\nunsigned32" +
      "\030\005 \001(\rB\017Z\rproto/intjsonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_intjson_Numbers_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_intjson_Numbers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_intjson_Numbers_descriptor,
        new java.lang.String[] { "Label", "Signed64", "Unsigned64", "Signed32", "Unsigned32", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
